language: php
php:
  - 7.0

git:
  depth: 5

sudo: false

env:
  global:
    secure:

matrix:
  fast_finish: true

before_install:
  - composer config --global github-oauth.github.com "$GITHUB_TOKEN"

install:
  - composer install --prefer-dist --no-interaction

script:
  - composer test
  - composer cs-check
after_script:
  - composer upload-coverage
