language: php
php:
  - '7.0'
install: composer install --no-interaction
script:
  - vendor/bin/phpunit --colors --configuration="tests/phpunit.xml" --coverage-clover clover.xml
  - php vendor/bin/coverage-checker.php clover.xml 2