version: '2'
services:
  web:
      build: ./docker/nginx/
      ports:
          - 80:80
      volumes_from:
          - app
  php:
      build:
          context: ./docker/php7.0-fpm
          dockerfile: ./Dockerfile
      expose:
          - 9000
      volumes_from:
          - app
      tty: true
      working_dir: /var/www/unfinished
  app:
      build:
          context: ./docker/app
          dockerfile: ./Dockerfile
      volumes:
          - ./application:/var/www/unfinished
      command: "true"
  mysql:
      image: mysql:latest
      volumes_from:
          - data
      ports:
          - 3307:3306
      environment:
          MYSQL_ROOT_PASSWORD: 12345
          MYSQL_DATABASE: unfinished
          MYSQL_USER: unfinished
          MYSQL_PASSWORD: 12345
  data:
      image: mysql:latest
      volumes:
          - ./docker/mysql_data:/var/lib/mysql
      command: "true"
  memcached:
      image: memcached:latest
      expose:
          - 11211
      command: "memcached"
  redis:
      image: redis
      expose:
          - 6379
